import Head from 'next/head'
import Header from '../components/Header'
import TodoList from "../components/TodoList"
import styles from '../styles/Home.module.css'
import {useMoralis} from "react-moralis"

const supportChains = ["31337", "5"]
const chainName = {
  "5" : "Goerli",
  "31337" : "Hardhat(Local)"
}

export default function Home() {
  const {isWeb3Enabled, chainId} = useMoralis()
  return (
    <>
      <Head>
        <title>Decentralized Task Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Header/>
       {isWeb3Enabled ? (
        <div>
          {supportChains.includes(parseInt(chainId).toString()) ? (
            <div> 
              <h2>Chain Network : {chainName[parseInt(chainId).toString()]}</h2>
              <TodoList/>
            </div>
          ) 
          : (<div>Please Switch to a supported chain Network. The supported chain Network is Goerli</div>)}
        </div>
       ) : (<div>Please Connect to a Wallet</div>) }
      </main>
    </>
  )
}
